Controllers/FinderController.cs
using AspNetCoreServicesApp.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RideSharingApplication.Models;

namespace RideSharingApplication.Controllers
{
    public class FinderController : Controller
    {

        private readonly ITripService tripService;

        public FinderController(ITripService _tripService)
        {
            this.tripService = _tripService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Trip obj)
        {

            tripService.AddTrip(obj);

            return RedirectToAction("Index");
        }

    }
}

Controllers/OurCarsController.cs
using Microsoft.AspNetCore.Mvc;
using RideSharingApplication.Data;
using RideSharingApplication.Models;
using RideSharingApplication.Services.Interfaces;

namespace RideSharingApplication.Controllers
{
    public class OurCarsController : Controller
    {

        private readonly ICarService carService;

        public OurCarsController(ICarService _carService)
        {
            carService = _carService;
        }

    
        public IActionResult Index()
        {
            IEnumerable<Car> obCarList = carService.getAllCars();
            return View(obCarList);
        }
    }
}

Controllers/WhatWeOfferController.cs
using Microsoft.AspNetCore.Mvc;

namespace RideSharingApplication.Controllers
{
    public class WhatWeOfferController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RideSharingApplication</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/b.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RideSharingApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">RideSharing</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor02">
              <ul class="navbar-nav me-auto">
                <li class="nav-item active">
                  <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                    <span class="visually-hidden">(current)</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" asp-controller="WhatWeOffer" asp-action="Index">What we offer</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" asp-controller="OurCars" asp-action="Index">Our Cars</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" asp-controller="Finder" asp-action="Index">Finder</a>
                </li>
              </ul>
              <partial name="_LoginPartial" />
            </div>
          </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>