Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RideSharingApplication.Models;
using System.Diagnostics;

namespace RideSharingApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SignUpController.cs
using Microsoft.AspNetCore.Mvc;

namespace RideSharingApplication.Controllers
{
    public class SignUpController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/css/stylesheet2.css">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>

  <body onload="typeWriter()">
    
      <div class="container" id="principalImg">
          <p id="type-effect"></p>
          <a asp-controller="SignUp" asp-action="Index" type="button" class="btn btn-primary" style="margin-left:100px; width:200px;">Sign Up</a>
          <button type="button" class="btn btn-primary" style="width:200px;">Log In</button>
      </div>

      <script>
            var i = 0;
            var txt = "Don't travel alone: share your location.";
            var speed = 30;

            function typeWriter() {
              if (i < txt.length) {
                document.getElementById("type-effect").innerHTML += txt.charAt(i);
                i++;
                setTimeout(typeWriter, speed);
              }
            }
            

        </script>

        <div class="row" style="border-left: solid; border-right:solid; border-width: 1px; margin-top: 5%;">

            <div class="col-sm-3" style="height:300px;">
                <p style="font-size:80px;">What is RideSharing?</p>
            </div>

            <div class="col-sm-9" style="height: 300px; padding-left:200px; padding-top: 50px; font-size: 20px;">
                <p> <span id="fLetter">A</span> ridesharing company is a company that, via websites and mobile apps, matches passengers with drivers of vehicles for hire that, unlike taxicabs, cannot legally be hailed from the street.</p>
            </div>

        </div>

        <div class="row" style="border-left: solid; border-right:solid; border-width: 1px; margin-top: 5%;">

            <div class="col-sm-9" style="height: 300px; padding-top: 50px; font-size: 20px;">
                <p> <span id="fLetter">W</span>hile using internet-based ride-sharing services, passengers and drivers can experience trust between people, share their information, and spend what would otherwise be idle time with each other; doing so may promote a more positive social interaction while sharing their journey.</p>
            </div>

            <div class="col-sm-3" style="height:180px; padding-top:20px;">
                <p style="font-size:70px;">And why use it?</p>
            </div>

        </div>

        <div style="text-align:center;">
            <p style="font-size: 40px;">What people say about us:</p>
        </div>

        <div class="row" style="height:500px; border-top: solid; border-width:1px;">

            <div class="col-sm-4">
                <div class="profile" style="background-image: url(/Resources/person1.jpg); background-size:cover; box-shadow: 5px 10px #888888;">

                </div>

                <p class="say">"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rutrum ex purus."</p>
                <p class="who">-Maria</p>
            </div>

            <div class="col-sm-4">
                <div class="profile" style="background-image: url(/Resources/person2.jpg); background-size:cover; box-shadow: 5px 10px #888888;">

                </div>
                <p class="say">"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rutrum ex purus."</p>
                <p class="who">-Andra</p>
            </div>

            <div class="col-sm-4">
                <div class="profile" style="background-image: url(/Resources/person3.jpg); background-size:cover; box-shadow: 5px 10px #888888;">

                </div>
                <p class="say">"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rutrum ex purus."</p>
                <p class="who">-Mihai</p>
            </div>

        </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>

</html>